<?php
/**
 * Plugin Name: Sugaring Certification WPBakery Page
 * Description: Adds an editable Sugaring Certification landing-page element to WPBakery without changing the active theme.
 * Version: 1.0.0
 * Requires Plugins: js_composer
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
define( 'SCW_URL', plugin_dir_url( __FILE__ ) );

function scw_assets() { wp_enqueue_style( 'scw-landing', SCW_URL . 'assets/css/landing.css', array(), '1.1.0' ); }
add_action( 'wp_enqueue_scripts', 'scw_assets' );

function scw_body_class( $classes ) {
	if ( is_singular() && has_shortcode( get_post_field( 'post_content', get_queried_object_id() ), 'sugaring_certification_landing' ) ) { $classes[] = 'scw-page'; }
	return $classes;
}
add_filter( 'body_class', 'scw_body_class' );

function scw_defaults() {
	return array( 'eyebrow'=>'Reserve your spot', 'headline'=>'Certified in Sugaring<br>Just Two Days', 'intro'=>'Sugar Sphere Dallas is excited to offer hands-on professional sugaring certification. Learn a profitable, in-demand service and leave ready to confidently serve clients.', 'date'=>'August 30–31, 2026', 'location'=>'Sugar Sphere Dallas, Fairview, TX 75069', 'price'=>'$749 deposit', 'button_text'=>'Enroll Now', 'button_url'=>'#', 'business_title'=>'Add a profitable, in-demand service to your beauty business', 'business_copy'=>'Sugaring is a natural hair removal method that appeals to clients who want a skin-friendly, effective alternative. Build a loyal client base with a service that delivers visible results.', 'instructor_name'=>'Learn from Latasha Quinn', 'instructor_bio'=>'Hi, I’m Latasha, a licensed esthetician and certified sugar practitioner with years of experience. I created this certification to give beauty professionals the hands-on training, confidence and technique to add sugaring to their services.', 'contact_email'=>'info@sugarspheredallas.com', 'contact_phone'=>'Click here to text us', 'contact_address'=>'341 Town Place, Suite 47, Fairview, Texas 75069' );
}
function scw_image_url( $id, $fallback ) { $url = $id ? wp_get_attachment_image_url( absint( $id ), 'full' ) : ''; return $url ? $url : SCW_URL . 'assets/images/' . $fallback; }

function scw_render( $atts ) {
	$a = shortcode_atts( scw_defaults(), $atts, 'sugaring_certification_landing' );
	$link = function_exists( 'vc_build_link' ) ? vc_build_link( $a['button_url'] ) : array( 'url' => $a['button_url'] );
	$button_url = ! empty( $link['url'] ) ? $link['url'] : '#';
	$hero = scw_image_url( $a['hero_image'] ?? '', 'hero-hands.png' ); $detail = scw_image_url( $a['detail_image'] ?? '', 'sugaring-detail.png' ); $instructor = scw_image_url( $a['instructor_image'] ?? '', 'instructor-fixed.png' ); $portrait = scw_image_url( $a['portrait_image'] ?? '', 'portrait-fixed.png' );
	$reviews = function_exists('vc_param_group_parse_atts') ? vc_param_group_parse_atts( $a['reviews'] ?? '' ) : array();
	$faqs = function_exists('vc_param_group_parse_atts') ? vc_param_group_parse_atts( $a['faqs'] ?? '' ) : array();
	if ( ! $reviews ) { $reviews = array(array('quote'=>'Latasha is a true professional—she teaches the art of sugaring with passion and makes the process feel simple.','name'=>'Aaliyah'),array('quote'=>'I walked away confident and ready to begin offering sugaring in my own beauty business.','name'=>'Nikki'),array('quote'=>'My first time getting a sugar wax and the experience was smooth and professional.','name'=>'Myriam')); }
	if ( ! $faqs ) { $faqs = array(array('question'=>'Do I need experience?','answer'=>'No experience is required.'),array('question'=>'What’s the difference between sugaring and waxing?','answer'=>'Sugaring uses a natural paste and a different removal technique.'),array('question'=>'Will I learn a full Brazilian in this class?','answer'=>'Yes, the course covers the full foundational service.'),array('question'=>'Do I need a license for this class?','answer'=>'Please review local licensing requirements before offering services.')); }
	$e = static function( $v ) { return esc_html( $v ); }; ob_start(); ?>
<div class="scw-landing">
 <nav class="scw-nav"><img src="<?php echo esc_url( SCW_URL.'assets/images/logo-fixed.png' ); ?>" alt="Sugar Sphere Dallas"><div><a href="#scw-details">Class Details</a><a href="#scw-curriculum">Curriculum</a><a href="#scw-faq">FAQs</a><a href="#scw-about">About</a><a href="#scw-contact">Contact</a><a class="scw-button" href="<?php echo esc_url($button_url); ?>"><?php echo $e($a['button_text']); ?></a></div></nav>
 <section class="scw-hero" style="--scw-hero:url('<?php echo esc_url($hero); ?>')"><div class="scw-inner"><div class="scw-hero-copy"><i><?php echo $e($a['eyebrow']); ?></i><h1><?php echo wp_kses_post($a['headline']); ?></h1><p><?php echo $e($a['intro']); ?></p><p class="scw-meta"><span><b>Dates</b><?php echo $e($a['date']); ?></span><span><b>Location</b><?php echo $e($a['location']); ?></span></p><a class="scw-button" href="<?php echo esc_url($button_url); ?>"><?php echo $e($a['button_text']); ?></a></div><img class="scw-portrait" src="<?php echo esc_url($portrait); ?>" alt="Instructor portrait"></div></section>
 <section id="scw-details" class="scw-section scw-panel"><div class="scw-inner"><header><h2>Get certified in two days in our 16-hour, hands-on foundational sugaring course.</h2></header><div class="scw-info"><div><b>Date</b><?php echo $e($a['date']); ?></div><div><b>Location</b><?php echo $e($a['location']); ?></div><div><b>Early-bird enrollment</b><?php echo $e($a['price']); ?></div><div><b>Regular price</b>Limited seats available</div></div><article class="scw-card"><h3>Deposit</h3><p>Deposit is non-refundable. It goes toward your enrollment and secures your seat. The balance must be paid before class.</p></article></div></section>
 <section class="scw-section"><div class="scw-inner scw-split"><div><h2><?php echo $e($a['business_title']); ?></h2><p><?php echo $e($a['business_copy']); ?></p></div><img src="<?php echo esc_url($detail); ?>" alt="Sugaring treatment"></div></section>
 <section class="scw-section scw-panel"><div class="scw-inner scw-centered"><h2>Why should you get certified in sugaring?</h2><div class="scw-benefits"><span>Add a sought-after service to your menu.</span><span>Grow your client base and revenue.</span><span>Learn a complete foundational technique.</span><span>Deliver a client-friendly experience.</span></div><a class="scw-button" href="<?php echo esc_url($button_url); ?>"><?php echo $e($a['button_text']); ?></a></div></section>
 <section id="scw-curriculum" class="scw-section"><div class="scw-inner"><header><h2>What’s included in your certification</h2></header><div class="scw-columns"><article class="scw-card"><h3>What you will receive</h3><ul><li>Hands-on practice and live demos</li><li>Professional sugaring techniques</li><li>Certificate of completion</li><li>Student resource guide</li><li>Foundational product knowledge</li><li>Ongoing community support</li><li>Professional protocol materials</li></ul></article><article class="scw-card"><h3>What you will learn</h3><ul><li>Full body service fundamentals</li><li>Proper product handling</li><li>Client consultation and aftercare</li><li>Skin preparation and sanitation</li><li>How to create your service flow</li><li>Speed and efficiency techniques</li><li>Pricing and business tips</li></ul></article><article class="scw-card"><h3>Who this is for</h3><ul><li>Licensed estheticians</li><li>Beauty professionals</li><li>Service providers ready to grow</li><li>New and experienced providers</li><li>Beauty students and graduates</li><li>Anyone expanding their menu</li><li>Professionals who value results</li></ul></article></div></div></section>
 <section id="scw-about" class="scw-section scw-panel"><div class="scw-inner scw-split"><div><i>Meet your instructor</i><h2><?php echo $e($a['instructor_name']); ?></h2><p><?php echo $e($a['instructor_bio']); ?></p></div><img src="<?php echo esc_url($instructor); ?>" alt="Instructor"></div></section>
 <section class="scw-section"><div class="scw-inner"><header><h2>Client reviews</h2></header><div class="scw-columns"><?php foreach($reviews as $r): ?><article class="scw-card scw-review"><p>“<?php echo $e($r['quote']??''); ?>”</p><i>— <?php echo $e($r['name']??''); ?></i></article><?php endforeach; ?></div></div></section>
 <section id="scw-faq" class="scw-section scw-panel"><div class="scw-inner"><header><h2>Sugaring certification — frequently asked questions</h2></header><?php foreach($faqs as $f): ?><details><summary><?php echo $e($f['question']??''); ?></summary><p><?php echo $e($f['answer']??''); ?></p></details><?php endforeach; ?></div></section>
 <section id="scw-contact" class="scw-section scw-panel"><div class="scw-inner scw-split"><div><i>Any questions?</i><h2>Can’t make this date?</h2><p>Drop your info and we’ll keep you posted about upcoming certification dates and open seats.</p><h3>Get in touch</h3><p><?php echo $e($a['contact_phone']); ?><br><?php echo $e($a['contact_email']); ?><br><?php echo $e($a['contact_address']); ?></p></div><div class="scw-card scw-form"><p>Name</p><p>Phone</p><p>Email</p><p>Message</p><a class="scw-button" href="#">Submit</a></div></div></section>
</div><?php return ob_get_clean();
}
add_shortcode( 'sugaring_certification_landing', 'scw_render' );

function scw_vc_map() {
	if ( ! function_exists( 'vc_map' ) ) return;
	vc_map( array('name'=>'Sugaring Certification Landing','base'=>'sugaring_certification_landing','category'=>'Content','description'=>'Editable PSD-matched landing page for Salient/WPBakery.','params'=>array(
		array('type'=>'textfield','heading'=>'Eyebrow','param_name'=>'eyebrow','value'=>'Reserve your spot'),array('type'=>'textarea','heading'=>'Headline (use &lt;br&gt; for a line break)','param_name'=>'headline','value'=>'Certified in Sugaring<br>Just Two Days'),array('type'=>'textarea','heading'=>'Hero introduction','param_name'=>'intro'),array('type'=>'textfield','heading'=>'Date','param_name'=>'date','value'=>'August 30–31, 2026'),array('type'=>'textfield','heading'=>'Location','param_name'=>'location'),array('type'=>'textfield','heading'=>'Price','param_name'=>'price','value'=>'$749 deposit'),array('type'=>'textfield','heading'=>'Button text','param_name'=>'button_text','value'=>'Enroll Now'),array('type'=>'vc_link','heading'=>'Button link','param_name'=>'button_url'),array('type'=>'attach_image','heading'=>'Hero background image','param_name'=>'hero_image'),array('type'=>'attach_image','heading'=>'Hero portrait','param_name'=>'portrait_image'),array('type'=>'textarea','heading'=>'Business title','param_name'=>'business_title'),array('type'=>'textarea','heading'=>'Business copy','param_name'=>'business_copy'),array('type'=>'attach_image','heading'=>'Sugaring image','param_name'=>'detail_image'),array('type'=>'textfield','heading'=>'Instructor name','param_name'=>'instructor_name'),array('type'=>'textarea','heading'=>'Instructor bio','param_name'=>'instructor_bio'),array('type'=>'attach_image','heading'=>'Instructor image','param_name'=>'instructor_image'),array('type'=>'param_group','heading'=>'Reviews','param_name'=>'reviews','params'=>array(array('type'=>'textarea','heading'=>'Quote','param_name'=>'quote'),array('type'=>'textfield','heading'=>'Name','param_name'=>'name'))),array('type'=>'param_group','heading'=>'FAQs','param_name'=>'faqs','params'=>array(array('type'=>'textfield','heading'=>'Question','param_name'=>'question'),array('type'=>'textarea','heading'=>'Answer','param_name'=>'answer'))),array('type'=>'textfield','heading'=>'Contact email','param_name'=>'contact_email'),array('type'=>'textfield','heading'=>'Contact phone','param_name'=>'contact_phone'),array('type'=>'textarea','heading'=>'Contact address','param_name'=>'contact_address') ) ) );
}
add_action( 'vc_before_init', 'scw_vc_map' );
